### ISSUE TITLE
Prerendering instead of ssr

### ISSUE THREAD

**Issue by anaelbe** [nuxt/vue-meta#134]
Since i can't use SSR, i tried to use vue-meta with the spa-prerender one, which doesn't seems get along well.
While being in dev mode, metas are injected properly, but when running build, assets are generated without errors, but also without any meta injection.

Any known issues on issues with PhantomJS ?

**Comment by sanderfish** [comment]
I would like to know more about using vue-meta in combination with [prerender-spa-plugin](https://github.com/chrisvfritz/prerender-spa-plugin) as well.

**Comment by hofman-p** [comment]
Yes, an answer would be very nice about this

**Comment by Felwin** [comment]
Just did it, works fine, just need a little tweaking.
As vue-meta is working asynchronously you need to pass Phantom options in order to prerender that correctly.
I just need the title and the description; description was not set on parent component (App.vue) but only on child (home, contact etc.) so it was quite easy, I added : 
captureAfterElementExists: "meta[name='description']"
and it works great.

For more complex things I guess you would need to use an event adding to prerender-spa-plugin phantom options : 
captureAfterDocumentEvent: 'custom-post-render-event',
and creating the 'custom-post-render-event' using changed() in vue-meta

**Comment by devmattrick** [comment]
I'm also having some issues with this. When not codesplitting routes, it works perfectly fine for me, but when adding a split point per route, any vue-meta information that is passed doesn't seem to get picked up by prerender-spa-plugin.

**Comment by manniL** [comment]
Stale. Please ping/answer here if the issue persists.
