### ISSUE TITLE
No way to update page title dynamically.

### ISSUE THREAD

**Issue by yekver** [nuxt/vue-meta#318]
Let's assume there is a page with infinite scroll. Page contains a bunch of articles and each article that is right now on a viewport must updates page title.
Currently there is no possibility to provide `vmid` fot the `title` property, so I have to manage `title` to keep active only current article title and flush the rest.

**Comment by manniL** [comment]
I don't see a reason for providing `vmid` for a title.
use Vuex.

Example https://codesandbox.io/s/8l2nj616nj

**Comment by yekver** [comment]
Thank you for example, but I wonder why title is so special from other meta tags? This is quite strange because all of them (including title) are unique in `<head></head>` section.

**Comment by manniL** [comment]
Hey ☺️ 

I think `title` has no VMID capabilities because nobody thought about a case where the title was switched based on components. 

Do you think `vmid` capabilities would really help to use the *right* title in your case? 🤔 
If so, feel free to send in a PR ☺️ 

PS: While normal `meta` tags can be present as an array (e.g. http://ogp.me/#array), which is useful in some cases, `title` can't be present more than once.
