### ISSUE TITLE
head bodyAttrs not reactive on initial page load

### ISSUE THREAD

**Issue by drewbaker** [nuxt/vue-meta#376]
### Version

[v2.8.0](https://github.com/nuxt.js/releases/tag/v2.8.0)

### Reproduction link

[https://codesandbox.io/s/codesandboxnuxt-ewiy9](https://codesandbox.io/s/codesandboxnuxt-ewiy9)

### Steps to reproduce

In a Layout, use the head() function to set a class using bodyAttrs from Vuex, then on a Pages mounted event change that class in the store, it does not change the head on a new page load. But it is reactive from click events or when browsing around the site and having mounted fire that way. It's just that initial page load that doesn't seem to be reactive.

### What is expected ?

That head() bodyAttrs is reactive at all times.

### What is actually happening?

The page comes off the server with a body class of "light" but is changed on mounted() to "dark", but the head() method doesn't catch that change.

It will work as intended if you browse between Home and About.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9301">#c9301</a>)</em></sub></div>

**Comment by pimlie** [comment]
Transferred this to vue-meta. In short, the workaround is to use $nextTick in your mounted hook to set the dark theme (both if you are using v1.x as v2.0rc)

Not sure what the exact problem is in vue-meta 1.x, but for 2.0rc the issue seems to be that vue-meta is also initialised in the mounted hook and all updates are blocked until vue-meta has initialized. Will add a fix for this behaviour in v2

**Comment by drewbaker** [comment]
Thanks Pim. I tired this:
```
  mounted() {
    this.$nextTick(() => {
      this.$store.commit("SET_COLOR_THEME", "dark");
    });
  }
```

But it still doesn't work on initial page load. I have it on the sandbox too if you want to see.

**Comment by pimlie** [comment]
Hmm, in that case I probably tested it wrong or had lockfile/npm cache issues and the $nextTick only works for v2rc. Its probably related in v1 due to the fact that the first metadata update after page hydration only removes the ssr flag but (in v1) but there is no ssr check on page load so your mutation does trigger a metadata update but doesnt apply anything

**Comment by drewbaker** [comment]
So I think I've run into this same bug when trying to set `title` in the head too, where `title` is coming from a Apollo query.

```
let page = this.page || {}
head() {
    return {
        title: page.title
    }    
},
apollo: {
    page: {// Query here}
}
```

When coming off the server, page.title is empty, and head() isn't waiting until it comes back before setting it. So essentially head() is useless for SEO tags set on the Page, they can only be set from `nuxtServerInit` and going through the Vuex.
