### ISSUE TITLE
Feature: New global option `onLoad`

### ISSUE THREAD

**Issue by ricardogobbosouza** [nuxt/vue-meta#476]
We could have a global option `onLoad` that would pass the current route and its meta data at startup and each change of route

**Comment by pimlie** [comment]
Not sure if I udnerstand you fully but that shounds like (a correctly functioning) `afterNavigation` that also runs on page load?

Im not sure that we can support this without adding specific code to support Nuxt transitions.

Also I am not sure yet if we want/need to support afterNavigation in vue-meta v3 still, see my pr of today. The reason we need afterNavigation is because meta updates are debounced with a setTimeout, in that pr Im suggesting to just use Vue watchers which means the setTimeout is removed and we should just be able to call nextTick in mounted to guarantee the metadata is updated.

**Comment by ricardogobbosouza** [comment]
I am taking as a basis this problem that we have [analytics-module](https://github.com/nuxt-community/analytics-module/issues/8) had for a long time.

With this new perspective v3 changes a lot.
Just not being a `setTimeout` is a big gain.

My question is how will we notify other modules that the metadata has changed?
