### ISSUE TITLE
$meta().addApp not being applied untill mounted

### ISSUE THREAD

**Issue by DRoet** [nuxt/vue-meta#481]
Hey @pimlie,

Just a quick followup question regarding the implementation of `vue-meta` + `vuetify`. I noticed the `.addApp()` method is not getting applied untill the application is fully mounted, which causes flickering in the theme when first loading the app, see: [codepen.](https://codesandbox.io/s/nuxtjs-vuetify-217-b0dfj) (the colors are black before they turn red)

Is there anything we can do to prevent this behaviour?

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/commit/8928a5f04eb7f8f7a183bf9fb873d1f3e3f3a1c6

**Comment by DRoet** [comment]
^^ those lines were added because otherwise the theme would trigger too early and wouldn't get applied because of: https://github.com/nuxt/vue-meta/blob/master/src/shared/additional-app.js#L17

**Comment by pimlie** [comment]
Its by design that vue-meta only renders meta-info once on page load. The 'best' time to do that is when all child components have been mounted, that way its unlikely that their metadata is changed again and we are updating meta data rapidly in succession.

You should be able though to call [`vm.$meta().refresh()`](https://vue-meta.nuxtjs.org/api/#meta-refresh) at any time. There is a slight change that an early refresh call will interfere for SSR sites as we do some extra initialization for those. But after looking at the mixin I dont think it should. To be sure please test that [callbacks](https://vue-meta.nuxtjs.org/api/#callback) are still called when you do an early refresh for a SSR page.

**Comment by DRoet** [comment]
Hmm when I try to call `refresh()` right after `set()` it throws an error because of https://github.com/nuxt/vue-meta/blob/master/src/client/refresh.js#L24.

however if I provide an overwrite:  `$root._vueMeta = true` it does work correctly

**Comment by pimlie** [comment]
Hmm, thats really not advised to do that. Firstly because `$root_vueMeta` should be an object, but `_vueMeta` is an internal var of us and I want to be able to change that when needed.

It seems you are just calling refresh too early, I guess you also call it directly in a beforeCreate hook? Can you delay that to a created hook? Cause then the root should be initialized by vue-meta

**Comment by DRoet** [comment]
Ah I thought our theme was using the `created` hook, but it is indeed the `beforeCreate` hook.

I will avoid modifying _vueMeta, I just thought it was interesting that the stylesheet would still get created correctly even when forcing it.

**Comment by amritk** [comment]
I don't believe this issue should be closed just yet

**Comment by amritk** [comment]
Alright for anyone landing here, found a new workaround 

https://github.com/vuetifyjs/vuetify/issues/9453#issuecomment-604217303
