### ISSUE TITLE
not data-n-head="true"?

### ISSUE THREAD

**Issue by Jonathan-Rao** [nuxt/vue-meta#524]
![(} $5U@804)YF5TPIJQ6ZR9](https://user-images.githubusercontent.com/16660755/75835977-5f950e80-5dfb-11ea-9310-38921f3e14e1.png)

**Comment by pimlie** [comment]
Im sorry, but what is the question?

**Comment by imranr970** [comment]
Hi @pimlie Please answer me you had callback logic in vue-meta.
So my question is how can I render whole nuxt? If callback returns true or callback set something to true? 
why I am doing this?
because I want to add external scripts and when I go to someother page using nuxt navigation external scripts doesnnt work.
Please note that scripts will be added to all over site not only one. So what is solution?

**Comment by pimlie** [comment]
@imranr970 You can add the script in a layout or in the head prop of your nuxt.config if you need a script to be available on all pages

**Comment by imranr970** [comment]
Can you tell me exact syntax using vue-meta?

**Comment by imranr970** [comment]
or in vuescript2

**Comment by pimlie** [comment]
See the docs: https://vue-meta.nuxtjs.org/api/#callback
