### ISSUE TITLE
Set head data on created

### ISSUE THREAD

**Issue by natashagp** [nuxt/vue-meta#532]
Hi, i'm trying to set the data to pass for the head dynamically, but it's not working. I tried passing to asyncData but it also didn't work.
It's a simple blog page to set the head tag dynamically.
PS.: I'm using Nuxt.js 
```js
data () {
    return {
      post: null
    }
  },
head () {
    return {
      title: this.post.titulo + ' - Blog'
    }
  },
created () {
    this.slug = this.$nuxt._route.params.slug
    if (this.slug === null || this.slug === '') {
      this.$router.push('/blog')
    } else {
      this.getPosts(this.slug).then((r) => {
        if (r.length && r.length === 0) {
          this.$router.push('/blog')
        } else {
          this.post = r[0]
        }
      })
    }
  },
```

**Comment by pimlie** [comment]
I dont see anything wrong with your code, are you sure `this.post.titulo` var has a value?

Also, when do you expect the title to be set? If you want to have it able on SSR then you need to use asyncData and make sure to return your this.getPosts promise so Nuxt knows to wait with rendering until the getPosts method has finished. This is because during SSR there is [no data reactivity](https://ssr.vuejs.org/guide/universal.html#data-reactivity-on-the-server)

Btw for the `- Blog` part you could maybe also use a titleTemplate. In your `nuxt.config` add a head section with a titleTemplate similar as here: https://nuxtjs.org/api/configuration-head#__layout

**Comment by natashagp** [comment]
It worked, I used the asyncData as you said and now it's working properly.
Thank you for the help 😁
