### ISSUE TITLE
title tag with unicode char and static page generation

### ISSUE THREAD

**Issue by AleeeKoi** [nuxt/vue-meta#577]
Hello!
I want to add an unicode character to the title tag.
I have already tried to add it like `&#128053;` or `&amp;#128053;` (disabling auto encoding using `__dangerouslyDisableSanitizers: ['title']` option doesn't help).
My site is generate using `nuxt generate` command.
After the generation process, the title tag is rendered and the unicode char is returned escaped.

Desired title tag after generation:
`<title>&#128053; - Lorem ipsum</title>`

Wrong generated title tag:
`<title>🐵 - Lorem ipsum</title>`

What is the correct way to do that?
Thank you

**Comment by pimlie** [comment]
What is your page encoding?
Do you use html minifying when runnign nuxt generate?

It might be terser that is translating the entity to the char, but not sure. Try to run nuxt generate with minifying disabled. 

Dont think this is caused by vue-meta at least, dont think we do anything special for the title tag

**Comment by AleeeKoi** [comment]
Hi @pimlie !
Currently utf8 (here it is: https://apedesign.net)
I'll try to disable minifying and let you know if it works asap.

Thank you
