### ISSUE TITLE
'Vue App' showing for a moment before loading the proper title

### ISSUE THREAD

**Issue by janswist** [nuxt/vue-meta#611]
I have an issue - I want proper title to be seen from the start, but instead for a second I see 'Vue App' title that is changed later to the proper name. How can I prevent it? I want my site to show only what I want to show - without 'Vue App' in the beginning. How to achieve that?

**Comment by pimlie** [comment]
Please show a reproduction of how you currently use vue-meta, ie do you use a spa or ssr?

**Comment by janswist** [comment]
I use basic Vue.js (not Nuxt.js) which is spa

**Comment by janswist** [comment]
Here is the basic reproduction: https://codesandbox.io/s/naughty-bas-sb5p8?file=/src/main.js

The difference is only in this that it shows `codesandbox` in the title instead of `Vue App`, but other than that it's the same problem.

**Comment by pimlie** [comment]
Thanks, unfortunately this is expected behaviour as this is just how SPA's work. They load generic html that satisfies _all_ pages and then on the client they check the current route and load all components + metainfo for that specific route. If you need to have the components + metainfo preloaded then you'll need to use ssr

See eg https://github.com/nuxt/vue-meta/issues/610 for a similar issue

**Comment by janswist** [comment]
I see. Is there any other way to put meta tags (I don't need it to be dynamic - just to have static title)? There is no `index.html` that I can put it in.

**Comment by pimlie** [comment]
But I guess you have something like a html document where you can put it? Ie the problem is that in a SPA the meta-tags are only rendered after all javascript files that contains your Vue-app are loaded and your Vue-app has been mounted. So how/where-ever you are loading your app bundle files, thats where you will also need to add the static meta tags.

**Comment by janswist** [comment]
Nope, it's all generated by Vue, unfortunately. In the older versions it was available, but now I'm left with `vue.config.js` https://cli.vuejs.org/config/.

**Comment by pimlie** [comment]
What about https://cli.vuejs.org/guide/html-and-static-assets.html#html ?

**Comment by janswist** [comment]
> What about https://cli.vuejs.org/guide/html-and-static-assets.html#html ?

Good find! Will dive into it - thank you!
