### ISSUE TITLE
Changed callback does not bind this to the vue instance

### ISSUE THREAD

**Issue by Zzombiee2361** [nuxt/vue-meta#626]
`this` is set to `metaInfo` object instead of vue instance. I'm not using nuxt so using arrow function result in `this` become undefined.

**Comment by pimlie** [comment]
So what do you suggest? To call changed with the rootVm as this only when not using Nuxt?

**Comment by Zzombiee2361** [comment]
Yeah, currently there is no way to access the vue instance when not using nuxt

**Comment by pimlie** [comment]
How/where do you define the changed function? I guess you are using the object syntax for `metaInfo`? If you instead use a function for that and have that return an object with the changed function _this_ should be the component you define it in

**Comment by Zzombiee2361** [comment]
Oh, yeah, you're right. It worked. But why can't `changed` callback just bind it to the current vue component?

**Comment by pimlie** [comment]
Which component is the current component for you? The root component, the component that caused the metainfo update to trigger of the component you defined it in?

At the moment we rely on basic vue/javascript to bind this, which I think is better because its more predictable to new users. Maybe an option could be to optionally bind it, will keep this in mind for v3

**Comment by Zzombiee2361** [comment]
I think the component which I defined it would make the most sense. Basically the same `this` as if I defined `metaInfo` as function. Thanks for your consideration
