### ISSUE TITLE
How can I externals in webpack

### ISSUE THREAD

**Issue by ntd0609** [nuxt/vue-meta#639]
I want to use externals library of webpack for this plugin but I can't find the way make it
Does anyone have an idea for this?
Thanks more

**Comment by pimlie** [comment]
Can you give a bit more information? I guess you are using vanilla Vue? Not nuxt or vue-cli? Why do you believe putting vue-meta in externals didnt work?

**Comment by ntd0609** [comment]
@pimlie Thanks you more, 
Right I build Vue by manual that run both client site and server build from webpack
I want to use external library that options in webpack
Some plugins have clear document about this, but I cant search any information for this.
If you have point please point to me.
Thanks

**Comment by pimlie** [comment]
@ntd0609 Im very sorry but its still not totally clear to me what you are trying to do. Could you maybe add some code/webpack config to explain?

If you mean you want to exclude vue-meta from your main bundle then I think that's in general not a good idea due to the nature of what vue-meta does. Having your meta data available/correct should be an integral part of your deployment and adding vue-meta as an external lib would probably only delay that unnecessarily
