### ISSUE TITLE
bodyAttrs usage

### ISSUE THREAD

**Issue by mirocklez** [nuxt/vue-meta#722]
Hi,
I have a question on the proper usage of `bodyAttrs`.
Let's say I have some body class set in `nuxt.config.js`, then I have a body class set in the `default layout` and another body class set in within a page.
As a result in the rendered page I will have set only the body class set withing the page and the other two (set in `nuxt.config.js` & `default layout`) will be lost.
Is there a proper way to save the classes alredy set in the `nuxt.config.js` and the `default layout` and just to add a new class in the page that is not replacing the other classes?
You can see in the demo below:
 - if you delete`bodyAttrs` in `index.vue` page the body class set in the `default layout` will appear
 - if you delete `bodyAtts` in the `default layout`  the body class set in the `nuxt.config.js` will appear

Reproduction link:
https://codesandbox.io/s/nuxt-body-attrs-is1pl

**Comment by bristl** [comment]
@miroslavgeorgiev Hello! If you find the answer, please write here!

**Comment by mirocklez** [comment]
> @miroslavgeorgiev Hello! If you find the answer, please write here!

Sure, will do - but still out of luck :(
For now I've settled with a solution of `bodyAttrs` usage in the `default layout` because I need a class set to body based on the `route name`.

**Comment by darkylmnx** [comment]
The issue even goes further, when I use plugins that add their own classes on the body, `bodyAttrs` on the layout or on any top-level component for that matter, seems to whipe out all the classes.

Here without Vue meta: https://jsfiddle.net/3brf8z2k/1/
Here without Vue meta: https://jsfiddle.net/3brf8z2k

As shown, vue-meta body classes overrides external classes, which is in some case out of our hands:
- cookie notice plugins
- visual plugins (3d, webgl, canvas or other stuff like that...)

Is there a way to tell vue-meta to append/prepend instead of replacing?

**Comment by archieDeveloper** [comment]
@miroslavgeorgiev your problem may be solved by using an array instead of a string:
[codesandbox.io](https://codesandbox.io/s/nuxt-body-attrs-forked-e7pud)

But another problem appears, if the template component adds the `test-class` and at the same time the page component adds the `test-class`, then an extra `test-class` will turn out.

But I don't have a solution to the problem of duplicating classes. But I came here looking for a solution to this problem.

**Comment by mirocklez** [comment]
> @miroslavgeorgiev your problem may be solved by using an array instead of a string:
> [codesandbox.io](https://codesandbox.io/s/nuxt-body-attrs-forked-e7pud)
> 
> But another problem appears, if the template component adds the `test-class` and at the same time the page component adds the `test-class`, then an extra `test-class` will turn out.
> 
> But I don't have a solution to the problem of duplicating classes. But I came here looking for a solution to this problem.

Thanks @archieDeveloper - good to know this 👍

**Comment by darkylmnx** [comment]
Still no clues for this issue?
It's really messes up apps with external plugins that classes to the body or html tag...
