### ISSUE TITLE
Is this project abandoned? + Alternatives!?

### ISSUE THREAD

**Issue by Remzi1993** [nuxt/vue-meta#799]
I'm using this library, but if I check the commits, the last is done in Aug 1, 2021 and no pull requests are accepted anymore.
I hope this project is still active because we all need it. If not I also hope there is an alternative.

I found this: https://github.com/unjs/unhead Has anybody experience with this?

**Comment by martonx** [comment]
2022 February was the last commit, but you're right, the question is very good. In theory nuxt use this package, but this package seems quite abandoned.

**Comment by Remzi1993** [comment]
> 2022 February was the last commit, but you're right, the question is very good. In theory nuxt use this package, but this package seems quite abandoned.

I tried this package and some things don't work anymore. I gave up and maybe I will use that other library I found.

**Comment by TheAlexLichter** [comment]
Check out https://github.com/vueuse/head from @harlan-zw ☺️

**Comment by Remzi1993** [comment]
> Check out https://github.com/vueuse/head from @harlan-zw ☺️

Thank you so much! I will check it out!

**Comment by Pierre-Saigot** [comment]
Thank you for the 'Head' project, it's amazing, truly better than Vue-Meta and it easily integrates with Vite.js. You're saving my life, thank you very much.

**Comment by sfreytag** [comment]
I'm migrating from Vue2, vue-cli and VueMeta to Vue3, Vite and, er, something... Thanks for the thread and info above. Having read it I think I have come to the same conclusion. Not least Nuxt3 seems to have adopted Unhead too - https://nuxt.com/docs/getting-started/seo-meta

I'll probably use the simpler unhead/vue rather than vueuse/head - https://unhead.harlanzw.com/integrations/vue/setup 

Differences described here: https://unhead.harlanzw.com/integrations/vue/vueuse-head

**Comment by TheAlexLichter** [comment]
Closing in favor of https://github.com/nuxt/vue-meta/issues/808
